INSERT INTO TBL_STUDENT (COURSE, NAME) VALUES ('ADS', 'Artur');

INSERT INTO TBL_STUDENT (COURSE, NAME) VALUES ('ADS', 'Pietro');

INSERT INTO TBL_STUDENT (COURSE, NAME) VALUES ('ADS', 'Ana Carorina');

